# Generated by Django 5.2.3 on 2025-07-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='isFavourite',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(),
        ),
    ]
